name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/erikvanzijst/arm-none-eabi-gcc:latest

    steps:
    - uses: actions/checkout@v3

    - name: Fix git safe dir
      run: git config --global --add safe.directory "*"
      
    - name: Run tests
      run: ( cd firmware/tests && make test )
    
    - name: Build firmware for v1_64
      run: ( cd firmware/gcc && make clean all BOARD=v1_64 )

    - name: Archive firmware v1_64
      uses: actions/upload-artifact@v3
      with:
        name: firmware-v1_64
        path: firmware/gcc/radioclock.*

    - name: Build firmware for v2_64
      run: ( cd firmware/gcc && make clean all BOARD=v2_64 )

    - name: Archive firmware v2_64
      uses: actions/upload-artifact@v3
      with:
        name: firmware-v2_64
        path: firmware/gcc/radioclock.*

    - name: Build firmware for v2_32
      run: ( cd firmware/gcc && make clean all BOARD=v2_32 )
      
    - name: Archive firmware v2_32
      uses: actions/upload-artifact@v3
      with:
        name: firmware-v2_32
        path: firmware/gcc/radioclock.*
