name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/erikvanzijst/arm-none-eabi-gcc:latest

    steps:
    - uses: actions/checkout@v3

    - name: Fix git safe dir
      run: git config --global --add safe.directory "*"
      
    - name: Run tests
      run: ( cd firmware/tests && make test )
    
    - name: Build firmware
      run: ( cd firmware/gcc && make )
      
    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: firmware/gcc/radioclock.*
